// GENERATED by scripts/gen-themes.mjs - edit the script, not this file.
export const THEMES = [
  {
    "id": "midnight",
    "label": "Midnight",
    "bg1": "#1a1d27"
  },
  {
    "id": "atlas",
    "label": "Atlas",
    "bg1": "#0b1220"
  },
  {
    "id": "graphite",
    "label": "Graphite",
    "bg1": "#171716"
  },
  {
    "id": "void",
    "label": "Void",
    "bg1": "#0b0c0d"
  },
  {
    "id": "nebula",
    "label": "Nebula",
    "bg1": "#150f1c"
  },
  {
    "id": "mono",
    "label": "Mono",
    "bg1": "#141415"
  },
  {
    "id": "ember",
    "label": "Ember",
    "bg1": "#1a130e"
  },
  {
    "id": "night",
    "label": "Night red",
    "bg1": "#140c0a"
  },
  {
    "id": "crimson",
    "label": "Night crimson",
    "bg1": "#0f0506"
  }
] as const
export type ThemeId = (typeof THEMES)[number]['id']
