from typing import Protocol, runtime_checkable
from astrolol.devices.base.models import (
    CameraStatus,
    ExposureParams,
    Image,
    MountStatus,
    SlewTarget,
    FocuserStatus,
)


@runtime_checkable
class ICamera(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def expose(self, params: ExposureParams) -> Image: ...
    async def abort(self) -> None: ...
    async def get_status(self) -> CameraStatus: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class IMount(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def slew(self, target: SlewTarget) -> None: ...
    async def stop(self) -> None: ...
    async def park(self) -> None: ...
    async def sync(self, target: SlewTarget) -> None: ...
    async def get_status(self) -> MountStatus: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class IFocuser(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def move_to(self, position: int) -> None: ...
    async def move_by(self, steps: int) -> None: ...
    async def halt(self) -> None: ...
    async def get_status(self) -> FocuserStatus: ...
    async def ping(self) -> bool: ...
