from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

from astrolol.devices.base.models import (
    CameraStatus,
    ExposureParams,
    FilterWheelStatus,
    Image,
    MountStatus,
    RotatorStatus,
    FocuserStatus,
    TrackingMode,
)

if TYPE_CHECKING:
    from astropy.coordinates import SkyCoord


@runtime_checkable
class ICamera(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def expose(self, params: ExposureParams) -> Image: ...
    async def abort(self) -> None: ...
    async def get_status(self) -> CameraStatus: ...
    async def set_cooler(self, enabled: bool, target_temperature: float | None) -> None: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class IMount(Protocol):
    """The full contract MountManager relies on (verified against every
    ``mount.<x>(`` call site in astrolol/mount/manager.py).

    ``set_time_utc`` and ``set_location`` are deliberately NOT part of this
    Protocol — MountManager calls them via ``hasattr`` duck-typing
    (``push_site_data``) and treats their absence as a no-op, since not every
    adapter needs external time/location (e.g. one that reads both from the
    mount itself). Every method below is called unconditionally, so any
    adapter implementing IMount must provide all of them.
    """
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def slew(self, coord: SkyCoord) -> None: ...
    async def stop(self) -> None: ...
    async def park(self) -> None: ...
    async def unpark(self) -> None: ...
    async def sync(self, coord: SkyCoord) -> None: ...
    async def set_tracking(self, enabled: bool, mode: TrackingMode | None = None) -> None: ...
    async def set_park_position(self) -> None: ...
    async def start_move(self, direction: str, rate: str) -> None: ...
    async def stop_move(self) -> None: ...
    async def meridian_flip(self) -> None: ...
    async def get_status(self) -> MountStatus: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class IFocuser(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def move_to(self, position: int) -> None: ...
    async def move_by(self, steps: int) -> None: ...
    async def halt(self) -> None: ...
    async def get_status(self) -> FocuserStatus: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class IFilterWheel(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def select_filter(self, slot: int) -> None: ...
    async def get_status(self) -> FilterWheelStatus: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class IRotator(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def get_status(self) -> RotatorStatus: ...
    async def ping(self) -> bool: ...
