from typing import Protocol, runtime_checkable
from astrolol.devices.base.models import (
    CameraStatus,
    ExposureParams,
    FilterWheelStatus,
    Image,
    MountStatus,
    RotatorStatus,
    SlewTarget,
    FocuserStatus,
)


@runtime_checkable
class ICamera(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def expose(self, params: ExposureParams) -> Image: ...
    async def abort(self) -> None: ...
    async def get_status(self) -> CameraStatus: ...
    async def set_cooler(self, enabled: bool, target_temperature: float | None) -> None: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class IMount(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def slew(self, target: SlewTarget) -> None: ...
    async def stop(self) -> None: ...
    async def park(self) -> None: ...
    async def unpark(self) -> None: ...
    async def sync(self, target: SlewTarget) -> None: ...
    async def set_tracking(self, enabled: bool) -> None: ...
    async def meridian_flip(self) -> None: ...
    async def get_status(self) -> MountStatus: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class IFocuser(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def move_to(self, position: int) -> None: ...
    async def move_by(self, steps: int) -> None: ...
    async def halt(self) -> None: ...
    async def get_status(self) -> FocuserStatus: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class IFilterWheel(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def select_filter(self, slot: int) -> None: ...
    async def get_status(self) -> FilterWheelStatus: ...
    async def ping(self) -> bool: ...


@runtime_checkable
class IRotator(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def get_status(self) -> RotatorStatus: ...
    async def ping(self) -> bool: ...
