"""Registers the INDI mount proxy (astrolol_indi_mount_proxy.py) with astrolol's indiserver.

indiserver's FIFO `start` command takes a bare executable, so a small launcher script
named after the proxy is written to the INDI run directory; it pins astrolol's Python
interpreter and the REST API URL.
"""
from __future__ import annotations

import shlex
import sys
from pathlib import Path
from typing import Any

import structlog

from plugins.eqmod.astrolol_indi_mount_proxy import DEVICE

logger = structlog.get_logger()

LAUNCHER_NAME = "astrolol-indi-mount-proxy"
PROXY_SCRIPT = Path(__file__).resolve().parent / "astrolol_indi_mount_proxy.py"


def write_launcher(run_dir: Path, api_url: str) -> Path:
    run_dir.mkdir(parents=True, exist_ok=True)
    path = run_dir / LAUNCHER_NAME
    path.write_text(
        "#!/bin/sh\n"
        "# astrolol INDI mount proxy: shows astrolol's mount to INDI clients (PHD2, snooping\n"
        "# drivers). Not a real mount driver: it relays to the astrolol REST API.\n"
        "# Generated by astrolol's eqmod plugin; do not edit.\n"
        f"exec {shlex.quote(sys.executable)} {shlex.quote(str(PROXY_SCRIPT))} --api {shlex.quote(api_url)}\n"
    )
    path.chmod(0o755)
    return path


class IndiProxyRegistration:
    """Keeps the proxy registered as an indiserver startup driver according to the settings."""

    def __init__(self, indi_manager: Any, run_dir: Path) -> None:
        self._manager = indi_manager
        self._run_dir = run_dir
        self._active: tuple[bool, str] | None = None

    @property
    def launcher_path(self) -> Path:
        return self._run_dir / LAUNCHER_NAME

    async def apply(self, enabled: bool, api_url: str) -> None:
        wanted = (enabled, api_url)
        if wanted == self._active:
            return  # unchanged: don't restart the proxy (PHD2 would lose it)
        if self._manager is None:
            if enabled:
                logger.warning("eqmod.indi_proxy_unavailable", reason="INDI support is not available")
            self._active = wanted
            return
        launcher = str(self.launcher_path)
        if self._active is not None and self._active[0]:
            await self._manager.remove_startup_driver(launcher)
        if enabled:
            write_launcher(self._run_dir, api_url)
            await self._manager.add_startup_driver(launcher)
        self._active = wanted
        logger.info("eqmod.indi_proxy_configured", enabled=enabled, api_url=api_url, launcher=launcher)

    def status(self) -> dict[str, Any]:
        enabled, api_url = self._active or (False, None)
        server = getattr(self._manager, "_server", None)
        return {
            "enabled": enabled,
            "api_url": api_url,
            "indi_available": self._manager is not None,
            "indiserver_running": bool(getattr(self._manager, "_started", False)),
            "loaded": str(self.launcher_path) in getattr(server, "_loaded_drivers", set()),
            "launcher": str(self.launcher_path),
            "device_name": DEVICE,
        }
