"""Sequencer interface: protocol, public models, events and errors (no implementation)."""

from astrolol.core.sequencer.errors import (
    InvalidRequest,
    PreflightFailed,
    SequencerBusy,
    SequencerError,
    SequencerNotRunning,
    TaskLocked,
    TaskNotFound,
)
from astrolol.core.sequencer.models import (
    Activity,
    Actor,
    Boundary,
    ExposureGroup,
    GroupProgress,
    ImagingTask,
    Interruption,
    Lane,
    LaneRuntime,
    PreflightIssue,
    PreflightReport,
    QueueEntry,
    RunOutcome,
    RunState,
    SequencerStatus,
    Stall,
    StallKind,
    TargetRef,
    TaskRuntime,
    TaskStatus,
)
from astrolol.core.sequencer.service import Sequencer

__all__ = [
    "Activity",
    "Actor",
    "Boundary",
    "ExposureGroup",
    "GroupProgress",
    "ImagingTask",
    "Interruption",
    "InvalidRequest",
    "Lane",
    "LaneRuntime",
    "PreflightFailed",
    "PreflightIssue",
    "PreflightReport",
    "QueueEntry",
    "RunOutcome",
    "RunState",
    "Sequencer",
    "SequencerBusy",
    "SequencerError",
    "SequencerNotRunning",
    "SequencerStatus",
    "Stall",
    "StallKind",
    "TargetRef",
    "TaskLocked",
    "TaskNotFound",
    "TaskRuntime",
    "TaskStatus",
]
