/** @type {import('tailwindcss').Config} */

// Colours are CSS variables (src/themes.css, generated by scripts/gen-themes.mjs) so the palette
// can be switched at runtime from Options. Stock colour names are redirected rather than renamed:
// `text-slate-400` or `bg-emerald-500/20` follow the active palette. Only shades 100-900 exist.
const v = (name) => `rgb(var(--c-${name}) / <alpha-value>)`
const ramp = (name) =>
  Object.fromEntries([100, 200, 300, 400, 500, 600, 700, 800, 900].map((s) => [s, v(`${name}-${s}`)]))

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}', '../astrolol/plugins/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Geist', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      colors: {
        ...Object.fromEntries(
          ['slate', 'sky', 'blue', 'cyan', 'teal', 'emerald', 'green', 'amber', 'yellow', 'orange',
           'rose', 'red', 'violet', 'purple', 'indigo'].map((n) => [n, ramp(n)]),
        ),
        surface: {
          DEFAULT: v('surface'),
          raised: v('surface-raised'),
          overlay: v('surface-overlay'),
          border: v('surface-border'),
        },
        accent: {
          DEFAULT: v('accent'),
          dim: v('accent-dim'),
          fg: v('accent-fg'),
        },
        status: {
          connected: v('status-connected'),
          error: v('status-error'),
          busy: v('status-busy'),
          idle: v('status-idle'),
        },
        // Two chart series that stay distinguishable in every palette, and six categories.
        series: { 1: v('series-1'), 2: v('series-2') },
        cat: Object.fromEntries([1, 2, 3, 4, 5, 6].map((i) => [i, v(`cat-${i}`)])),
      },
    },
  },
  plugins: [],
}
